# Generated by Django 5.2.11 on 2026-02-21 23:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.CharField(blank=True, max_length=100, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=7, null=True)),
                ('occupation', models.CharField(blank=True, max_length=17, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address_interior_number', models.CharField(blank=True, max_length=26, null=True)),
                ('address_complement', models.TextField(blank=True, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('address_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=24, null=True)),
                ('reset_password_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('reset_password_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
